### ISSUE TITLE
Waiver UX

### ISSUE THREAD

**Issue by maggie-j-liu** [oliver-ni/contestdojo#2]
Hi! Super cool website :D

When filling out the waiver; there's a couple things that could be improved:
1. There's a section that asks you to fill out a parent if different from parent 1 (I think, I don't have a screenshot of the exact section), but the form doesn't let you submit if it's not filled out.
2. There's not really any indication of what fields are required and what fields are not (usually it's a red asterisk), so it was a bit difficult to figure out what needed to be filled out to submit the form.

(would be happy to help pr, but I think waivers are stored in firebase?)

**Comment by oliver-ni** [comment]
Waivers are stored as Markdown and rendered with custom directive syntax. Currently there's no way to mark a field as optional/required. I'll work on adding that when I get a chance, but if you'd like to contribute, that part's here:

https://github.com/oliver-ni/contestdojo/blob/main/components/WaiverEditor/components.tsx

**Comment by maggie-j-liu** [comment]
Thanks! Would it be possible to get an example of how a waiver looks in markdown, for testing?

**Comment by oliver-ni** [comment]
This is what BMT's waiver looks like: https://mystb.in/RaceReplacementTaking

Also the code's kind of a mess, it might take a little messing around to get it to run properly, sorry about that.

**Comment by oliver-ni** [comment]
Implemented in 0bb2df25cd713bdaa759da4a34dc55f60e8fbfd1
